name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run tauri build

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: PSM-Player
          path: |
            src-tauri/target/release/*.exe
            src-tauri/target/release/bundle/**/*.msi
